services:
  postgres:
    image: postgres:16-alpine
    container_name: expense_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/src/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  pgdata:
